name: tabebi
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+2

environment:
  sdk: '>=2.19.4 <3.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  http: ^0.13.5
  shared_preferences: ^2.0.20
  connectivity_plus: ^3.0.3
  flutter_bloc: ^8.1.2
  firebase_core: ^2.8.0
  image_picker: ^0.8.7
  flutter_localizations:
    sdk: flutter
  flutter_svg: ^2.0.4  
  firebase_auth: ^4.4.0
  country_picker: ^2.0.20
  sms_autofill: ^2.3.0
  intl: 0.18.0
  file_picker: ^5.2.10
  permission_handler: ^10.2.0
  path_provider: ^2.0.15
  share_plus: 6.0.0
  uni_links: ^0.5.1
  firebase_messaging: ^14.6.1
  flutter_local_notifications: ^14.0.0+1
  cached_network_image: ^3.2.3
  webview_flutter: ^4.2.1
  url_launcher: ^6.1.11
  flutter_pdfview: ^1.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter

 
  flutter_lints: ^2.0.0


flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/svg/
    - assets/languages/
  fonts:
    - family: MyEngFont
      fonts:
        - asset: assets/font/eng/PlusJakartaSans-Regular.ttf
        - asset: assets/font/eng/PlusJakartaSans-Bold.ttf
          weight: 700        
        - asset: assets/font/eng/PlusJakartaSans-ExtraBold.ttf
          weight: 800       
        - asset: assets/font/eng/PlusJakartaSans-ExtraLight.ttf
          weight: 200     
        - asset: assets/font/eng/PlusJakartaSans-Light.ttf
          weight: 300        
        - asset: assets/font/eng/PlusJakartaSans-Medium.ttf
          weight: 500  
        - asset: assets/font/eng/PlusJakartaSans-SemiBold.ttf
          weight: 600 
    - family: MyArabicFont
      fonts:
        - asset: assets/font/arabic/NeoSansArabicRegular.ttf
        - asset: assets/font/arabic/NeoSansArabicBlack.ttf
          weight: 700        
        - asset: assets/font/arabic/NeoSansArabicExtraBold.ttf
          weight: 800       
        - asset: assets/font/arabic/NeoSansArabicExtraLight.ttf
          weight: 200     
        - asset: assets/font/arabic/NeoSansArabicLight.ttf
          weight: 300        
        - asset: assets/font/arabic/NeoSansArabicMedium.ttf
          weight: 500  
        - asset: assets/font/arabic/NeoSansArabicBold.ttf
          weight: 600        
