// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyChoNd4aFFe-2rrV0oSXz1k_W1bp1COaP0',
    appId: '1:391264764757:android:7358c811d00541272fa5dc',
    messagingSenderId: '391264764757',
    projectId: 'tabebi-bc72f',
    storageBucket: 'tabebi-bc72f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA2S3pchz4Yx-MDFE12qWLswdMjWt6hgvo',
    appId: '1:391264764757:ios:71750b5d298c8f9c2fa5dc',
    messagingSenderId: '391264764757',
    projectId: 'tabebi-bc72f',
    storageBucket: 'tabebi-bc72f.appspot.com',
    androidClientId: '391264764757-c9bk7o7fjrhpu2pibjcg6uof78nlmgoe.apps.googleusercontent.com',
    iosClientId: '391264764757-ku8s4b8vedpsnmommtavive8h0j5gmcf.apps.googleusercontent.com',
    iosBundleId: 'com.app.tabebiuser',
  );
}
